export const SET_AUTHORIZATION_STATE = 'SET_AUTHORIZATION_STATE';
export const SET_USER_INFORMATION = 'SET_USER_INFORMATION';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
